/slam_toolbox:
  ros__parameters:
    # Robot frame params
    base_frame: base_link
    map_frame: map
    odom_frame: odom
    scan_topic: /scan
    mode: mapping

    # SLAM params
    use_sim_time: false
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 20.0
    min_range: 0.15
    max_update_rate: 10.0
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000

    # Scan matching params
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    minimum_time_interval: 0.5
